### ISSUE TITLE
'package:angular/core/scope.dart': Failed assertion: line 352 pos 12: 'isAttached' is not true.

### ISSUE THREAD

**Issue by mulander** [angular/angular.dart#1602]
When I start up my Angular Dart application I see the following exception + stack trace but it seems to have no visible impact on the way the application works.

```
'package:angular/core/scope.dart': Failed assertion: line 352 pos 12: 'isAttached' is not true.

STACKTRACE:
#0      Scope.on (package:angular/core/scope.dart:352:12)
#1      ElementBinder.bind (package:angular/core_dom/element_binder.dart:307:15)
#2      ViewFactory._bindTagged (package:angular/core_dom/view_factory.dart:79:36)
#3      ViewFactory._link (package:angular/core_dom/view_factory.dart:119:24)
#4      ViewFactory.call (package:angular/core_dom/view_factory.dart:58:10)
#5      BoundTranscludingComponentFactory.call.<anonymous closure>.<anonymous closure> (package:angular/core_dom/transcluding_component_factory.dart:112:54)
#6      _rootRunUnary (dart:async/zone.dart:899)
#7      _ZoneDelegate.runUnary (dart:async/zone.dart:506)
#8      _onRunUnary.<anonymous closure> (package:angular/core/zone.dart:122:63)
#9      VmTurnZone._onRunBase (package:angular/core/zone.dart:104:16)
#10     _onRunUnary (package:angular/core/zone.dart:122:17)
#11     _CustomZone.runUnary (dart:async/zone.dart:801)
#12     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:496)
#13     _Future._propagateToListeners (dart:async/future_impl.dart:579)
#14     _Future._propagateMultipleListeners (dart:async/future_impl.dart:431)
#15     _Future._propagateToListeners (dart:async/future_impl.dart:458)
#16     _Future._completeWithValue (dart:async/future_impl.dart:339)
#17     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:401)
#18     _rootRun (dart:async/zone.dart:888)
#19     _ZoneDelegate.run (dart:async/zone.dart:499)
#20     _onScheduleMicrotask.<anonymous closure> (package:angular/core/zone.dart:127:45)
#21     RootScope._runAsyncFns (package:angular/core/scope.dart:923:25)
#22     RootScope.digest (package:angular/core/scope.dart:812:38)
#23     Scope.apply (package:angular/core/scope.dart:316:24)
#24     RootScope.RootScope.<anonymous closure> (package:angular/core/scope.dart:768:12)
#25     _rootRun (dart:async/zone.dart:892)
#26     _ZoneDelegate.run (dart:async/zone.dart:499)
#27     VmTurnZone._finishTurn (package:angular/core/zone.dart:168:21)
#28     VmTurnZone._onRunBase (package:angular/core/zone.dart:111:43)
#29     _onRunUnary (package:angular/core/zone.dart:122:17)
#30     _CustomZone.runUnary (dart:async/zone.dart:801)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:709)
#32     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:735)
```

**Comment by adarshaj** [comment]
@vmendi I have seen this happen in our app randomly, can you point to possible errors or how to go about debugging such issue in general? Also, any good guide to walk through the lifecycle of component?

tia!

**Comment by cedx** [comment]
Same problem here. I know that it's probably an implementation issue, but the error does not give any clue on how to fix it.
It would be productive to have a more meaningful message, like which component or scope property is involved in the issue.
Especially since I have exactly the same code on another project, and this error never appears (e.g. it's seems to be triggered by a component that is shared by the two projects).
