### ISSUE TITLE
Building Electron App using Angular

### ISSUE THREAD

**Issue by avstudios** [angular/angular.dart#1720]
I'm trying to run my angular app with Electron framework. I've created everything what I need using info from:
```https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md``` page.

Unfortunately I'm getting an error in terminal:
```Relative URL resolution requires a valid base URI
STACKTRACE:
Relative URL resolution requires a valid base URI
    at dart.wrapException (file:///Users/user/my_app/build/web/main.dart.js:3006:15)
    at dart.throwExpression (file:///Users/user/my_app/build/web/main.dart.js:3019:13)
    at closure380.dart.closure380.call$2 (file:///Users/user/my_app/build/web/main.dart.js:39830:11)
    at ModuleInjector.dart.ModuleInjector.getByKey$1 (file:///Users/user/my_app/build/web/main.dart.js:33921:26)```

I'm quite new to Angular so not sure if that is Angular or Electron problem. I'm appreciate for any help.

**Comment by avstudios** [comment]
I found the solution here:
http://stackoverflow.com/questions/28704577/angular-dart-relative-url-resolution-requires-a-valid-base-uri
